# Change these first
owner: st37infra # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: ST37 Home
    url: https://www.st37.fr
  - name: ST37 Skouting
    url: https://www.skouting.com/
  - name: ST37 Engarde Service
    url: https://engarde-service.com
  - name: ST37 Engarde Escrime
    url: https://www.engarde-escrime.com
  - name: ST37 Paasport
    url: https://www.paasport.st37.fr
  - name: ST37 Skouting Fencing
    url: https://fencing.skouting.com
  - name: ST37 AI Prod
    check: "tcp-ping"
    url: 52.211.208.47
    port: 9999
  - name: ST37 AI Dev
    check: "tcp-ping"
    url: dev-aist.st37.fr
    port: 9999

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.st37.fr
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/st37infra/upptime/master/assets/st37.svg
  faviconSvg: https://raw.githubusercontent.com/st37infra/upptime/master/assets/st37.svg
  name: Uptime Monitor
  # themeUrl: https://raw.githubusercontent.com/st37infra/upptime/master/assets/styles.css
  theme: night
  navbar:
    - title: Home
      href: https://www.st37.fr

i18n:
  footer: © ST37 Sport et Tecnologie

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
