# Change these first
owner: st37infra # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: ST37 Home
    url: https://www.st37.fr
  - name: ST37 Skouting
    url: https://skouting.st37.fr
  - name: ST37 Engarde Service
    url: https://engarde-service.com
  - name: ST37 Engarde Escrime
    url: https://www.engarde-escrime.com
  - name: ST37 Paasport
    url: https://www.paasport.st37.fr/
  - name: ST37 Skouting Industrie
    url: https://www.industrie.st37.fr/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.st37.fr
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page."
  introMessage: This is a sample status page which uses **real-time** data
  navbar:
    - title: Status
      href: /
    - title: ST37
      href: https://www.st37.fr

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
